name: Cherry Pick Bot

on:
  issue_comment:
    types: [created]

jobs:
  cherry-pick:
    if: contains(github.event.comment.body, '@.ymir cherry-pick') && github.event.comment.user.login == 'smallkirby'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        run: |
          uv python install
          uv sync --all-extras

      - name: Setup Git
        run: |
          git config --global user.name 'smallkirby-ymir[bot]'
          git config --global user.email '195134948+smallkirby-ymir[bot]@users.noreply.github.com'
          git fetch --all

      - name: Run Cherry Pick Script
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          PR_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
        run: uv run .github/scripts/cherry-picker.py
